import { Product, Restaurant } from "@/types";

// Helper function to create restaurant object
const createRestaurant = (
    id: string,
    slug: string,
    resName: string,
    duration: number = 25
): Restaurant => ({
    id,
    slug,
    resName,
    address: "123 Nguyen Hue, Q1, TP.HCM",
    longitude: 106.701317,
    latitude: 10.775658,
    rating: 4.5,
    openingTime: "06:00",
    closingTime: "22:00",
    phone: "0901234567",
    imageURL: null,
    merchantId: "testmerchantid",
    enabled: true,
    totalReview: 100,
    distance: 1.5,
    duration,
    products: [],
    cate: [],
});

// Dummy food data for testing grid layout
export const DUMMY_FOODS: Product[] = [
    {
        id: "dummy-1",
        slug: "special-beef-pho",
        productName: "Special Beef Pho (Pho Dac Biet)",
        description: "Traditional Vietnamese noodle soup with rare beef, brisket, and meatballs",
        imageURL: "https://images.unsplash.com/photo-1528607929212-9566d2f23f02?w=600&q=90",
        categoryName: "Vietnamese",
        categoryId: "CAT001",
        volume: 100,
        available: true,
        restaurant: createRestaurant("RES001", "pho-ha-noi", "Pho Ha Noi", 25),
        totalReview: 234,
        rating: 4.8,
        productSizes: [{ id: "S1", sizeName: "Regular", price: 2.2, sizeId: "M" }],
    },
    {
        id: "dummy-2",
        slug: "grilled-pork-bun-cha",
        productName: "Grilled Pork Bun Cha",
        description: "Vietnamese grilled pork with vermicelli noodles and fresh herbs",
        imageURL: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
        categoryName: "Vietnamese",
        categoryId: "CAT001",
        volume: 120,
        available: true,
        restaurant: createRestaurant("RES002", "bun-cha-obama", "Bun Cha Obama", 20),
        totalReview: 189,
        rating: 4.6,
        productSizes: [{ id: "S2", sizeName: "Regular", price: 2.0, sizeId: "M" }],
    },
    {
        id: "dummy-3",
        slug: "pepperoni-pizza",
        productName: "Pepperoni Pizza",
        description: "Classic pizza with pepperoni and mozzarella cheese",
        imageURL: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80",
        categoryName: "Pizza",
        categoryId: "CAT002",
        volume: 80,
        available: true,
        restaurant: createRestaurant("RES003", "pizza-hut-express", "Pizza Hut Express", 30),
        totalReview: 456,
        rating: 4.5,
        productSizes: [{ id: "S3", sizeName: "Large", price: 3.2, sizeId: "L" }],
    },
    {
        id: "dummy-4",
        slug: "korean-bbq-bulgogi",
        productName: "Korean BBQ Bulgogi",
        description: "Marinated beef grilled to perfection with Korean spices",
        imageURL: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=400&q=80",
        categoryName: "Korean",
        categoryId: "CAT003",
        volume: 150,
        available: true,
        restaurant: createRestaurant("RES004", "korean-bbq-house", "Korean BBQ House", 35),
        totalReview: 312,
        rating: 4.7,
        productSizes: [{ id: "S4", sizeName: "Regular", price: 2.8, sizeId: "M" }],
    },
    {
        id: "dummy-5",
        slug: "sushi-platter",
        productName: "Sushi Platter Deluxe",
        description: "Assorted fresh sushi with salmon, tuna, and eel",
        imageURL: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&q=80",
        categoryName: "Japanese",
        categoryId: "CAT004",
        volume: 60,
        available: true,
        restaurant: createRestaurant("RES005", "sushi-tokyo", "Sushi Tokyo", 40),
        totalReview: 278,
        rating: 4.9,
        productSizes: [{ id: "S5", sizeName: "Regular", price: 4.0, sizeId: "M" }],
    },
    {
        id: "dummy-6",
        slug: "bubble-tea-milk",
        productName: "Bubble Tea Milk",
        description: "Creamy milk tea with chewy tapioca pearls",
        imageURL: "https://images.unsplash.com/photo-1598428452686-5c0c5b0b0b5a?w=400&q=80",
        categoryName: "Drinks",
        categoryId: "CAT005",
        volume: 50,
        available: true,
        restaurant: createRestaurant("RES006", "tra-sua-gong-cha", "Tra Sua Gong Cha", 15),
        totalReview: 567,
        rating: 4.4,
        productSizes: [{ id: "S6", sizeName: "Large", price: 1.2, sizeId: "L" }],
    },
    {
        id: "dummy-7",
        slug: "broken-rice-com-tam",
        productName: "Broken Rice (Com Tam)",
        description: "Vietnamese broken rice with grilled pork, egg, and pickled vegetables",
        imageURL: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80",
        categoryName: "Vietnamese",
        categoryId: "CAT001",
        volume: 110,
        available: true,
        restaurant: createRestaurant("RES007", "com-tam-sai-gon", "Com Tam Sai Gon", 25),
        totalReview: 423,
        rating: 4.6,
        productSizes: [{ id: "S7", sizeName: "Regular", price: 1.8, sizeId: "M" }],
    },
    {
        id: "dummy-8",
        slug: "banh-mi-sandwich",
        productName: "Banh Mi Sandwich",
        description: "Vietnamese baguette with pate, cold cuts, and fresh vegetables",
        imageURL: "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400&q=80",
        categoryName: "Vietnamese",
        categoryId: "CAT001",
        volume: 70,
        available: true,
        restaurant: createRestaurant("RES008", "banh-mi-huynh-hoa", "Banh Mi Huynh Hoa", 20),
        totalReview: 678,
        rating: 4.9,
        productSizes: [{ id: "S8", sizeName: "Regular", price: 1.5, sizeId: "M" }],
    },
    {
        id: "dummy-9",
        slug: "pad-thai",
        productName: "Pad Thai Noodles",
        description: "Stir-fried rice noodles with shrimp, tofu, and tamarind sauce",
        imageURL: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=400&q=80",
        categoryName: "Thai",
        categoryId: "CAT006",
        volume: 90,
        available: true,
        restaurant: createRestaurant("RES001", "pho-ha-noi", "Pho Ha Noi", 25),
        totalReview: 345,
        rating: 4.5,
        productSizes: [{ id: "S9", sizeName: "Regular", price: 2.5, sizeId: "M" }],
    },
    {
        id: "dummy-10",
        slug: "chicken-fried-rice",
        productName: "Chicken Fried Rice",
        description: "Wok-fried rice with chicken, vegetables, and soy sauce",
        imageURL: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&q=80",
        categoryName: "Chinese",
        categoryId: "CAT007",
        volume: 100,
        available: true,
        restaurant: createRestaurant("RES003", "pizza-hut-express", "Pizza Hut Express", 30),
        totalReview: 234,
        rating: 4.3,
        productSizes: [{ id: "S10", sizeName: "Regular", price: 2.0, sizeId: "M" }],
    },
    {
        id: "dummy-11",
        slug: "ramen-bowl",
        productName: "Tonkotsu Ramen",
        description: "Rich pork bone broth ramen with chashu pork and soft-boiled egg",
        imageURL: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80",
        categoryName: "Japanese",
        categoryId: "CAT004",
        volume: 85,
        available: true,
        restaurant: createRestaurant("RES005", "sushi-tokyo", "Sushi Tokyo", 40),
        totalReview: 512,
        rating: 4.8,
        productSizes: [{ id: "S11", sizeName: "Regular", price: 3.5, sizeId: "M" }],
    },
    {
        id: "dummy-12",
        slug: "beef-stir-fry",
        productName: "Beef Stir Fry",
        description: "Tender beef strips stir-fried with bell peppers and onions",
        imageURL: "https://images.unsplash.com/photo-1546069901-5ec3c8c8e2c3?w=400&q=80",
        categoryName: "Chinese",
        categoryId: "CAT007",
        volume: 95,
        available: true,
        restaurant: createRestaurant("RES004", "korean-bbq-house", "Korean BBQ House", 35),
        totalReview: 189,
        rating: 4.4,
        productSizes: [{ id: "S12", sizeName: "Regular", price: 2.6, sizeId: "M" }],
    },
];

