// Sample menu items data for your table
const menuItemsData = [
    {
        id: "MI001",
        name: "Boiled Plantain",
        category: "Main Course",
        price: "£9.99",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-15",
        dateUpdated: "2024-01-20",
    },
    {
        id: "MI002",
        name: "YAM PORRIDGE",
        category: "Main Course",
        price: "£9.99",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-16",
        dateUpdated: "2024-01-21",
    },
    {
        id: "MI003",
        name: "AMALA",
        category: "Traditional",
        price: "£11.99",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-17",
        dateUpdated: "2024-01-22",
    },
    {
        id: "MI004",
        name: "EBA",
        category: "Traditional",
        price: "£11.99",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-18",
        dateUpdated: "2024-01-23",
    },
    {
        id: "MI005",
        name: "Seafood Salad",
        category: "Salad",
        price: "£5.99",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-19",
        dateUpdated: "2024-01-24",
    },
    {
        id: "MI006",
        name: "African Salad",
        category: "Salad",
        price: "£8.99",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-20",
        dateUpdated: "2024-01-25",
    },
    {
        id: "MI007",
        name: "Whole catfish with rice and vegetables",
        category: "Seafood",
        price: "£13.99",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-21",
        dateUpdated: "2024-01-26",
    },
    {
        id: "MI008",
        name: "Special Shrimp Deluxe",
        category: "Seafood",
        price: "£12.99",
        stockQty: 0,
        specialStatus: "Featured",
        status: "Enabled",
        dateAdded: "2024-01-22",
        dateUpdated: "2024-01-27",
    },
    {
        id: "MI009",
        name: "RICE AND DODO",
        category: "Main Course",
        price: "£11.99",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-23",
        dateUpdated: "2024-01-28",
    },
    {
        id: "MI010",
        name: "ATA RICE",
        category: "Rice Dishes",
        price: "£12.00",
        stockQty: 0,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-24",
        dateUpdated: "2024-01-29",
    },
    {
        id: "MI011",
        name: "Jollof Rice",
        category: "Rice Dishes",
        price: "£10.99",
        stockQty: 15,
        specialStatus: "Popular",
        status: "Enabled",
        dateAdded: "2024-01-25",
        dateUpdated: "2024-01-30",
    },
    {
        id: "MI012",
        name: "Pepper Soup",
        category: "Soup",
        price: "£14.99",
        stockQty: 8,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-26",
        dateUpdated: "2024-01-31",
    },
    {
        id: "MI013",
        name: "Pounded Yam",
        category: "Traditional",
        price: "£13.50",
        stockQty: 0,
        specialStatus: "--",
        status: "Disabled",
        dateAdded: "2024-01-27",
        dateUpdated: "2024-02-01",
    },
    {
        id: "MI014",
        name: "Chicken Suya",
        category: "Grilled",
        price: "£16.99",
        stockQty: 12,
        specialStatus: "Spicy",
        status: "Enabled",
        dateAdded: "2024-01-28",
        dateUpdated: "2024-02-02",
    },
    {
        id: "MI015",
        name: "Moi Moi",
        category: "Traditional",
        price: "£7.99",
        stockQty: 20,
        specialStatus: "--",
        status: "Enabled",
        dateAdded: "2024-01-29",
        dateUpdated: "2024-02-03",
    },
];

// Additional sample categories for filter options
const categories = ["Main Course", "Traditional", "Salad", "Seafood", "Rice Dishes", "Soup", "Grilled"];

// Status options
const statusOptions = ["Enabled", "Disabled", "Out of Stock"];

// Special status options
const specialStatusOptions = ["--", "Featured", "Popular", "New", "Spicy", "Vegetarian", "Chef's Special"];

export { menuItemsData, categories, statusOptions, specialStatusOptions };
