import Footer from "@/components/layout/layout/Footer";
import Header from "@/components/layout/layout/Header";
import type { Metadata } from "next";
import { Manrope, Roboto_Serif } from "next/font/google";
import "./globals.css";
const robotoSerif = Roboto_Serif({
        subsets: ["latin"],
        variable: "--font-roboto-serif",
        weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const manrope = Manrope({
        subsets: ["latin"],
        variable: "--font-manrope",
        weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
        title: "Create Next App",
        description: "Generated by create next app",
};

export default function RootLayout({
        children,
}: Readonly<{
        children: React.ReactNode;
}>) {
        return (
                <html lang="en">
                        <body className={`${robotoSerif.variable} ${manrope.variable}`}>
                                <Header />
                                <main> {children}</main>
                                <Footer />
                        </body>
                </html>
        );
}
